# Site wide configuration

title:            Coven 2-4 October
locale:           en_US
url:              https://en.coven.nu


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

# Event info
event:
  name: Coven
  tagline: 'a witch <a href="/nordic-larp/">LARP</a>'
  logo: skull.jpg
  description: 'A <a href="/nordic-larp/">Live Action Roleplaying</a> event taking place near Stockholm 2-4 October 2015'
  email: english@coven.nu
#  twitter: CovenLARP
#  facebook: CovenLARP
  google:
    analytics: 
    verify: 

# Cache invalidation
css:
  timestamp: 2015051302

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
